continue=true
log-level=warn

# HTTP/HTTPS performance
max-connection-per-server=8
split=8
min-split-size=10M

# Reliability
retry-wait=2
connect-timeout=10
timeout=30

# macOS / APFS
file-allocation=falloc

# BitTorrent
dht-listen-port=25641
listen-port=25641
follow-torrent=mem

# Metalink
follow-metalink=mem
metalink-location=de

# UI
summary-interval=0
