version: 2
root-markers:
  - .git/
  - package.json
  - pyproject.toml
  - Dockerfile
  - nvim/
lint-debounce: 1s

tools:
  sh-shellcheck: &sh-shellcheck
    lint-command: 'shellcheck -f gcc -x'
    lint-source: 'shellcheck'
    lint-formats:
      - '%f:%l:%c: %trror: %m'
      - '%f:%l:%c: %tarning: %m'
      - '%f:%l:%c: %tote: %m'

  sh-shfmt: &sh-shfmt
    format-command: 'shfmt -ci -s -bn'
    format-stdin: true

  dockerfile-hadolint: &dockerfile-hadolint
    lint-command: 'hadolint'
    lint-formats:
      - '%f:%l %m'

  python-pylint: &python-pylint
    lint-command: 'pylint --output-format text --score no --msg-template {path}:{line}:{column}:{C}:{msg} ${INPUT}'
    lint-stdin: false
    lint-formats:
      - '%f:%l:%c:%t:%m'
    lint-offset-columns: 1
    lint-category-map:
      I: H
      R: I
      C: I
      W: W
      E: E
      F: E

  python-black: &python-black
    format-command: 'black --quiet -'
    format-stdin: true

  python-flake8: &python-flake8
    lint-command: 'flake8 --stdin-display-name ${INPUT} -'
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: %m'

  javascript-eslint: &javascript-eslint
    lint-command: 'eslint_d -f visualstudio --stdin --stdin-filename ${INPUT}'
    lint-ignore-exit-code: true
    lint-stdin: true
    lint-formats:
      - "%f(%l,%c): %tarning %m"
      - "%f(%l,%c): %rror %m"

  javascript-prettier: &javascript-prettier
    format-command: "prettier_d_slim --stdin --stdin-filepath ${INPUT}"
    format-stdin: true

  lua-lua-format: &lua-lua-format
    format-command: 'lua-format -i --no-keep-simple-function-one-line --no-break-after-operator --column-limit=100 --no-use-tab --single-quote-to-double-quote --indent-width=2'
    format-stdin: true

languages:
  dockerfile:
    - <<: *dockerfile-hadolint

  sh:
    - <<: *sh-shellcheck
    - <<: *sh-shfmt

  javascript:
    - <<: *javascript-prettier
    - <<: *javascript-eslint

  typescript:
    - <<: *javascript-prettier
    - <<: *javascript-eslint

  vue:
    - <<: *javascript-prettier
    - <<: *javascript-eslint

  python:
    - <<: *python-black
    - <<: *python-pylint

  lua:
    - <<: *lua-lua-format
