#!/usr/bin/env lua

-- Add the sketchybar module to the package cpath
package.cpath = package.cpath .. ";/Users/" .. os.getenv("USER") .. "/.local/share/sketchybar_lua/?.so"

-- Require the sketchybar module
sbar = require("sketchybar")

-- init Aerospace client (disabled: migrated to Rift)
-- local Aerospace = require("lib.aerospace")
-- local aerospace = Aerospace.new()
-- while not aerospace:is_initialized() do
--   os.execute("sleep 0.1") -- wait for connection, not the best workaround
-- end
-- sbar.aerospace = aerospace

-- Bundle the entire initial configuration into a single message to sketchybar
-- This improves startup times drastically
sbar.begin_config()
require("init")
-- sbar.hotload(true)
sbar.end_config()

-- Run the event loop of the sketchybar module
sbar.event_loop()
