#!/usr/bin/osascript

# Required parameters:
# @raycast.schemaVersion 1
# @raycast.title Ghostty (new window)
# @raycast.mode silent

# Optional parameters:
# @raycast.icon images/ghostty.png

set termName to "Ghostty"

tell application termName
    if it is running
        tell application "System Events" to tell process termName
            click menu item "New Window" of menu "File" of menu bar 1
        end tell
    else
        activate
    end if
end tell
