#!/bin/bash

# Required parameters:
# @raycast.schemaVersion 1
# @raycast.title Rift: Mode Master-Stack
# @raycast.mode silent

# Optional parameters:
# @raycast.icon 🪟
# @raycast.packageName Rift

# Documentation:
# @raycast.description Switch active workspace to master-stack (dwm) layout

/opt/homebrew/bin/rift-cli execute workspace set-layout master_stack
