#!/usr/bin/env bash

# Required parameters:
# @raycast.schemaVersion 1
# @raycast.title Kitty (new window)
# @raycast.mode silent

# Optional parameters:
# @raycast.icon images/kitty.png

if pgrep -U "$(id -u)" -x kitty >/dev/null; then
  kitty --single-instance -d "$HOME"
else
  open -a "/Applications/kitty.app"
fi
