#!/bin/bash

# Required parameters:
# @raycast.schemaVersion 1
# @raycast.title Firefox (New Window)
# @raycast.mode silent

# Optional parameters:
# @raycast.icon images/firefox.png

open --new "/Applications/Firefox Developer Edition.app"

