#!/bin/bash

# Required parameters:
# @raycast.schemaVersion 1
# @raycast.title Rift: Promote to Master
# @raycast.mode silent

# Optional parameters:
# @raycast.icon 🪟
# @raycast.packageName Rift

# Documentation:
# @raycast.description Move focused window into the master area (master-stack only)

/opt/homebrew/bin/rift-cli execute layout promote-to-master
