#!/bin/bash

# Required parameters:
# @raycast.schemaVersion 1
# @raycast.title Rift: Toggle Stack
# @raycast.mode silent

# Optional parameters:
# @raycast.icon 🪟
# @raycast.packageName Rift

# Documentation:
# @raycast.description Toggle stacked (tabbed) state for the selected container

/opt/homebrew/bin/rift-cli execute layout toggle-stack
